# sourxce - https://www.youtube.com/watch?v=bndXPsRHPg0
using LinearAlgebra
using SparseArrays
using Images
using MAT


mtrxA = rand(10, 10)
mtrxATrans = mtrxA'
@show mtrxA[11] == mtrxA[1,2] # Matrices are stored as contigeous arrays

mtrxMult = mtrxA * mtrxATrans # Matrix multiplication

# Solving linear equations
vectB = rand(10)
solnX = mtrxA\vectB

@show norm(mtrxA * solnX - vectB) # should be negligible

# types
@show typeof(mtrxA) # Matrix has 2 dims
typeof(vectB) # Vector has 1 dim
# column vector generated by rand with 2 arguments is 2 dimensional
typeof(rand(10,1))
typeof(mtrxATrans) # is Adjoint and not array

# Find original matrix of the Adjoint
@show mtrxATrans.parent == mtrxA

# LU Factorization
luOfmtrxA = lu(mtrxA)
# check that the error is very small
luError = norm(luOfmtrxA.L * luOfmtrxA.U - luOfmtrxA.P * mtrxA)
isapprox(luError, 0.0; atol=eps(Float64), rtol=0) # doesn't work - TODO Find better solution
luError ≈ 0.0 # is same as above

# QR Factorization
qrOfmtrxA = qr(mtrxA)
norm(qrOfmtrxA.Q * qrOfmtrxA.R - mtrxA)

# Cholesky Factorization
cholOfmtrxA = cholesky(mtrxMult)
factorize(mtrxMult) # should return the Ckolesky as Matrix is positive definite
factorize(mtrxA) # will return most suitable one


# Generate different types of Matrices
mtrxI = I(3)
mtrxDiag = diagm([1,2,3])

# Sparse Linear Algebra
mtrxSparse = sprand(5, 5, 2/5)
# get all row indices of the sparse matrix
mtrxSparse.rowval
# get the indices of columns
mtrxSparse.colptr
# get actual values
mtrxSparse.nzval